<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/model/newLandscape.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/static\model\newLandscape.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Circle014.geometry}
      material={gltf.materials.plainWhite}
      position={[-0.14, 0.67, 0.08]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle015.geometry}
      material={gltf.materials.white}
      position={[0.01, 7.47, 0.08]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle016.geometry}
      material={gltf.materials.white}
      position={[0.01, 0.29, 0.08]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle017.geometry}
      material={gltf.materials.white}
      position={[0.01, 6.67, 0.08]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane006.geometry}
      material={gltf.materials.white}
      position={[-0.14, 0.67, 4.66]}
      scale={24.25}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane007.geometry}
      material={gltf.materials.white}
      position={[-0.14, -2.26, 4.66]}
      scale={24.25}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
