<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/model/rock1.glb -T
-->

<script>
    import { T } from "@threlte/core";
    import * as THREE from "three";
    import { useGltf, useDraco } from "@threlte/extras";
    import MeshTransmissionMaterial from "$lib/materials/MeshTransmissionMaterial.svelte";
    import { RectAreaLight } from "three";
    import { Edges } from "@threlte/extras";

    let { fallback, error, children, ref = $bindable(), ...props } = $props();
    const dracoLoader = useDraco();
    const gltf = useGltf("/model/rocks2.glb", { dracoLoader });
    const gltfWire = useGltf("/model/rocks2wire.glb", { dracoLoader });

    gltfWire.then((gltfWire) => {
        console.log("gltf", gltfWire);
    });

    const meshTransmissionConfig = {
        backside: true,
        samples: 8,
        resolution: 512,
        roughness: 0.1,
        thickness: 0.3,
        // ior: 1,
        chromaticAberration: 0.3,
        anisotropy: 1,
        distortion: 0.2,
        distortionScale: 0.3,
        temporalDistortion: 0.3,
        clearcoat: 1,
        attenuationDistance: 0.5,
        attenuationColor: "#fff",
        background: "#955cdb",
        color: "#ead9ff",
    };
</script>

<T.Group

    bind:ref
    dispose={false}
    {...props}
    position={[ 0.3138, -0.4987, 0.5202 ]}
    scale={[ 0.2, 0.2, 0.2 ]}

    rotation={[ 0.5288, -0.1501, -0.2077 ]}
>
    {#await gltf}
        {@render fallback?.()}
    {:then gltf}

        <T.PointLight color="#ffffff" intensity={0.4886} scale={[ 0.02, 0.02, 0.02 ]} position={[ 0.1836, 0.3113, 0.2508 ]} distance={19} power={7.3395} decay={3.4}/>

        <T.Mesh
            geometry={gltf.nodes.tripo_node_f589d329.geometry}
            position={[ 0, 0, 0 ]}
        >
            <MeshTransmissionMaterial {...meshTransmissionConfig} />
        </T.Mesh>

        {#await gltfWire}
            {@render fallback?.()}
        {:then gltfWire}
            <T.Mesh
                geometry={gltfWire.nodes.tripo_node_f589d329001.geometry}
                position={[0.0134, 0.014, -0.014]}
                scale={[0.76, 0.75, 0.59]}
                receiveShadow
                castShadow
            >
                <T.MeshStandardMaterial color="#ffffff" visible />
            </T.Mesh>
        {/await}

    {:catch err}
        {@render error?.({ error: err })}
    {/await}

    {@render children?.({ ref })}
</T.Group>
