<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/model/newLandscape.glb
-->

<script>
    import { T } from "@threlte/core";
    import {
        useGltf,
        useDraco,
        interactivity,
        Instance,
        InstancedMesh,
    } from "@threlte/extras";
    import { emissive } from "three/src/nodes/TSL.js";
    const dracoLoader = useDraco();
    let { fallback, error, children, ref = $bindable(), ...props } = $props();

    const gltf = useGltf("/model/newLandscape.glb", { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
    {#await gltf}
        {@render fallback?.()}
    {:then gltf}
        <T.Mesh
            geometry={gltf.nodes.Circle005.geometry}
            material={gltf.materials.plainWhite}
        />
        <T.Mesh
            geometry={gltf.nodes.Plane002.geometry}
            material={gltf.materials.white}
        />
        <T.Mesh
            geometry={gltf.nodes.Cylinder002.geometry}
            material={gltf.materials.plainWhite}
            position={[0.07, 0.67, 0]}
            rotation={[-Math.PI, 1.46, -Math.PI]}
        />
        <T.Mesh
            geometry={gltf.nodes.Circle008.geometry}
            material={gltf.materials.white}
            position={[0.07, 7.61, 0]}
        />
        <T.Mesh
            geometry={gltf.nodes.Circle009.geometry}
            material={gltf.materials.white}
            position={[0.07, 0.29, 0]}
        />
        <T.Mesh
            geometry={gltf.nodes.Circle001.geometry}
            material={gltf.materials.white}
            position={[0.08, 6.89, 0]}
            scale={5.62}
        />
    {:catch err}
        {@render error?.({ error: err })}
    {/await}

    {@render children?.({ ref })}
</T.Group>
